language: ruby
rvm:
  - 2.5
  - 2.6
env:
  matrix:
    - SOLIDUS_BRANCH=v2.7 DB=postgres
    - SOLIDUS_BRANCH=v2.8 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v2.7 DB=mysql
    - SOLIDUS_BRANCH=v2.8 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql
